//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _56f8205850dc6a2e92c791a67e91da6f_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("56f8205850dc6a2e92c791a67e91da6f-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _596b3e54cc44a20f1e443ba3eca8d4f7_preview_1752302836634 {
            get {
                object obj = ResourceManager.GetObject("596b3e54cc44a20f1e443ba3eca8d4f7-preview-1752302836634", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _841e5a4216765b1459006302765fea4f_preview_1752374247677 {
            get {
                object obj = ResourceManager.GetObject("841e5a4216765b1459006302765fea4f-preview-1752374247677", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9483d172_52d4_45a2_aee1_dec0253e4571_removalai_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("9483d172-52d4-45a2-aee1-dec0253e4571_removalai_preview (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9483d172_52d4_45a2_aee1_dec0253e4571_removalai_preview__2_1 {
            get {
                object obj = ResourceManager.GetObject("9483d172-52d4-45a2-aee1-dec0253e4571_removalai_preview (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9d2df9416c6d6c3f61c461e1423462cf_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("9d2df9416c6d6c3f61c461e1423462cf-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b6db6290574add7b907ade725bb69df9_preview_1752310246580 {
            get {
                object obj = ResourceManager.GetObject("b6db6290574add7b907ade725bb69df9-preview-1752310246580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b6db6290574add7b907ade725bb69df9_preview_17523102465801 {
            get {
                object obj = ResourceManager.GetObject("b6db6290574add7b907ade725bb69df9-preview-17523102465801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c7099787d22dc515999c3e164d29d6ee_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("c7099787d22dc515999c3e164d29d6ee-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d63992c4db49b2d8139a2569e2af46a1 {
            get {
                object obj = ResourceManager.GetObject("d63992c4db49b2d8139a2569e2af46a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e52ab9ea3f5fb3d6cf460789fd3be954_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("e52ab9ea3f5fb3d6cf460789fd3be954-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e52ab9ea3f5fb3d6cf460789fd3be954_removebg_preview__1___1_ {
            get {
                object obj = ResourceManager.GetObject("e52ab9ea3f5fb3d6cf460789fd3be954-removebg-preview (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f7cf653f_1503_4879_8e14_97b7f793d1d6_removalai_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("f7cf653f-1503-4879-8e14-97b7f793d1d6_removalai_preview (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fadb7a9954146795f296cde591fda75f_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("fadb7a9954146795f296cde591fda75f-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g {
            get {
                object obj = ResourceManager.GetObject("g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log_in_logo {
            get {
                object obj = ResourceManager.GetObject("log in logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
